blinking-cursor = true
performance = "High"
disable-unfocused-render = false
use-fork = false
line-height = 1.0
theme = ""
padding-x = 10.0
cursor = "|"
env-vars = []
option-as-alt = "false"
ignore-selection-fg-color = false

[navigation]
mode = "CollapsedTab"
color-automation = []
clickable = false
use-current-path = false
use-terminal-title = false
macos-hide-window-buttons = false

[window]
width = 600
height = 400
mode = "Windowed"

[background]
opacity = 0.5

[shell]
program = ""
args = ["--login"]

[fonts]
size = 18.0

[fonts.regular]
family = "cascadiamono"
weight = 400
style = "normal"

[fonts.bold]
family = "cascadiamono"
weight = 800
style = "normal"

[fonts.bold-italic]
family = "cascadiamono"
weight = 800
style = "italic"

[fonts.italic]
family = "cascadiamono"
weight = 400
style = "italic"

[developer]
enable-fps-counter = false
log-level = "OFF"

[bindings]
keys = []

[colors]
cursor = "#4CAF50"